Authorization: Bearer {{bearerToken}}

###
GET localhost:8080/welcome

###
GET localhost:8080/roles
Authorization: Bearer {{bearerToken}}

###
GET localhost:8080/hello
Authorization: Bearer {{bearerToken}}

###
POST localhost:8080/hello
Authorization: Bearer {{bearerToken}}
Content-Type: application/json

{
  "message": "test"
}

###
GET https://employee-api.szut.dev/qualifications
Authorization: Bearer {{bearerToken}}

###
GET https://employee-api.szut.dev/employees
Authorization: Bearer {{bearerToken}}

###
POST http://localhost:8080/projects
Authorization: Bearer {{bearerToken}}
Content-Type: application/json

{
  "name": "LF8-Projekt: Webservice Implementierung",
  "description": "Backend für die neue Projektverwaltungssoftware als Microservice.",
  "customerId": 101,
  "responsibleEmployeeId": 1,
  "startDate": "2025-10-01",
  "endDate": "2025-12-15",
  "status": "PLANNED",
  "employeeIds": [
    1,
    2
  ]
}

> {%
    client.global.set("projectId", response.body.id);
%}

###
GET http://localhost:8080/projects
Authorization: Bearer {{bearerToken}}

###
GET http://localhost:8080/projects/{{projectId}}
Authorization: Bearer {{bearerToken}}

###
PUT http://localhost:8080/projects/{{projectId}}
Authorization: Bearer {{bearerToken}}
Content-Type: application/json

{
  "name": "LF8-Projekt: Webservice Implementierung (Update)",
  "description": "Backend ist in der Umsetzung. Status wurde geändert.",
  "customerId": 101,
  "responsibleEmployeeId": 2,
  "startDate": "2025-10-01",
  "endDate": "2025-12-20",
  "status": "RUNNING",
  "employeeIds": [
    1,
    2,
    3
  ]
}

###
POST http://localhost:8080/projects
Authorization: Bearer {{bearerToken}}
Content-Type: application/json

{
  "name": "Projekt zum Löschen",
  "responsibleEmployeeId": 1
}

> {%
    client.global.set("projectIdToDelete", response.body.id);
%}

###
DELETE http://localhost:8080/projects/{{projectIdToDelete}}
Authorization: Bearer {{bearerToken}}